type: object
description: Various tracking system identifier strings.
properties:
  googleAnalytics:
    description: The Google Analytics tracking identifier string.
    type: string
    example: UA-XXXXX-YY
  googleTagManager:
    description: The Google Tag Manager tracking identifier string.
    type: string
    example: GTM-XXXXX
  gtagJs:
    description: The Google Analytics tracking identifier string for Google's Global Site Tag (gtag.js) service.
    type: string
    example: UA-XXXXX-YY
  facebookPixel:
    description: The Facebook Pixel tracking identifier string.
    type: string
    example: 1234567890
  segmentAnalytics:
    description: The Segment Analytics tracking identifier string.
    type: string
    example: 1234567890
  heapIo:
    description: The Heap.io tracking identifier string.
    type: string
    example: 1234567890
