get:
  x-products:
    - Core
  tags:
    - AML
  summary: Retrieve AML settings
  operationId: GetAmlSettings
  x-sdk-operation-name: getAmlSettings
  description: Retrieves confidence level settings for customer AML match scenarios.
  responses:
    '200':
      description: AML settings retrieved.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AmlSettings.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
put:
  x-products:
    - Core
  tags:
    - AML
  summary: Update AML settings
  operationId: PutAmlSettings
  x-sdk-operation-name: putAmlSettings
  description: |-
    Updates confidence level settings for customer AML match scenarios.

    For each scenario, set the degree of confidence to assign when a matching country,
    mismatching country, or no country is detected.

    Confidence levels:
    - **Very strong:** Very strong degree of confidence that the AML check is correct.
    - **Strong:** Strong degree of confidence that the AML check is correct.
    - **Medium:** Medium degree of confidence that the AML check is correct.
    - **Weak:** Weak degree of confidence that the AML check is correct.
    - **No confidence:** No confidence that the AML check is correct.
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AmlSettings.yaml
    description: Settings for AML searches.
    required: true
  responses:
    '200':
      description: AML settings updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AmlSettings.yaml
    '201':
      description: AML settings created.
      headers:
        Location:
          $ref: ../components/headers/Location.yaml
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AmlSettings.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
