parameters:
  - $ref: ../components/parameters/applicationId.yaml
get:
  x-products:
    - Users
  tags:
    - Application users
  summary: Retrieve an application instance settings
  operationId: GetApplicationInstanceSettings
  x-sdk-operation-name: get
  description: Retrieves installed application settings.
  responses:
    '200':
      description: Application instance settings retrieved.
      headers:
        Pagination-Total:
          $ref: ../components/headers/Pagination-Total.yaml
        Pagination-Limit:
          $ref: ../components/headers/Pagination-Limit.yaml
        Pagination-Offset:
          $ref: ../components/headers/Pagination-Offset.yaml
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Applications/ApplicationInstanceSettings.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
put:
  x-products:
    - Users
  tags:
    - Application users
  summary: Upsert an application instance settings
  operationId: PutApplicationInstanceSettings
  x-sdk-operation-name: upsert
  description: Creates or updates (upserts) an application instance settings.
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Applications/ApplicationInstanceSettings.yaml
  responses:
    '200':
      description: Application instance settings updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Applications/ApplicationInstanceSettings.yaml
    '201':
      description: Application instance settings created.
      headers:
        Location:
          $ref: ../components/headers/Location.yaml
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Applications/ApplicationInstanceSettings.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '422':
      $ref: ../components/responses/ValidationError.yaml
