parameters:
  - $ref: ../components/parameters/resourceId.yaml
post:
  x-products:
    - Full
    - Users
  tags:
    - Organizations
  summary: Update an organization's settings
  operationId: PutOrganizationSettings
  x-sdk-operation-name: settings
  description: >
    Updates an organization's settings.
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Organizations/OrganizationSettings.yaml
    description: Organization's settings.
    required: true
  responses:
    '200':
      description: Organization settings were updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Organizations/OrganizationSettings.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
