parameters:
  - $ref: ../components/parameters/resourceId.yaml
  - $ref: ../components/parameters/organizationId.yaml
get:
  tags:
    - Products
  summary: Retrieve a product
  operationId: GetProduct
  x-sdk-operation-name: get
  description: |
    Retrieve a product with specified identifier string.
  responses:
    '200':
      description: Product was retrieved successfully.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
  x-codeSamples:
    - lang: JavaScript
      source:
        $ref: '../code_samples/JavaScript/products@{id}/get.js'
put:
  tags:
    - Products
  summary: Upsert a product with predefined ID
  operationId: PutProduct
  x-sdk-operation-name: update
  description: |
    Create or update a product with predefined identifier string.
  requestBody:
    $ref: ../components/requestBodies/Product.yaml
  responses:
    '200':
      description: Product was updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '201':
      description: Product was created.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '422':
      $ref: ../components/responses/ValidationError.yaml
  x-codeSamples:
    - lang: JavaScript
      source:
        $ref: '../code_samples/JavaScript/products@{id}/put.js'
delete:
  tags:
    - Products
  summary: Delete a product
  operationId: DeleteProduct
  x-sdk-operation-name: delete
  description: |
    Delete a product with predefined identifier string.
  responses:
    '204':
      description: Product was deleted.
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
  x-codeSamples:
    - lang: JavaScript
      source:
        $ref: '../code_samples/JavaScript/products@{id}/delete.js'
