parameters:
  - $ref: ../components/parameters/organizationId.yaml
get:
  tags:
    - Products
  summary: Retrieve a list of products
  operationId: GetProductCollection
  description: |
    Retrieve a list of products
  parameters:
    - $ref: ../components/parameters/collectionLimit.yaml
    - $ref: ../components/parameters/collectionOffset.yaml
  responses:
    '200':
      description: A list of products was retrieved successfully
      headers:
        Rate-Limit-Limit:
          $ref: ../components/headers/Rate-Limit-Limit.yaml
        Rate-Limit-Remaining:
          $ref: ../components/headers/Rate-Limit-Remaining.yaml
        Rate-Limit-Reset:
          $ref: ../components/headers/Rate-Limit-Reset.yaml
        Pagination-Total:
          $ref: ../components/headers/Pagination-Total.yaml
        Pagination-Limit:
          $ref: ../components/headers/Pagination-Limit.yaml
        Pagination-Offset:
          $ref: ../components/headers/Pagination-Offset.yaml
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/Product.yaml
    '401':
      $ref: ../components/responses/AccessForbidden.yaml
post:
  tags:
    - Products
  summary: Create a Product
  operationId: PostProduct
  description: |
    Create a Product
  requestBody:
    $ref: ../components/requestBodies/Product.yaml
  responses:
    '201':
      description: Product was created
      headers:
        Rate-Limit-Limit:
          $ref: ../components/headers/Rate-Limit-Limit.yaml
        Rate-Limit-Remaining:
          $ref: ../components/headers/Rate-Limit-Remaining.yaml
        Rate-Limit-Reset:
          $ref: ../components/headers/Rate-Limit-Reset.yaml
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '401':
      $ref: ../components/responses/AccessForbidden.yaml
    '422':
      $ref: ../components/responses/InvalidDataError.yaml
