type: object
required:
  - name
properties:
  name:
    description: The property name.
    type: string
    maxLength: 50
    pattern: '^[@~\-\.\w]+$'
  description:
    description: The property description.
    type: string
  placeholder:
    description: The property placeholder.
    type: string
  default:
    description: The property default value.
    type: string
  required:
    description: Is property required.
    type: boolean
    default: false
