title: generic
allOf:
  - required:
      - type
    properties:
      type:
        description: The property type.
        type: string
        enum:
          - string
          - integer
          - number
          - boolean
  - $ref: ./CommonApplicationProperty.yaml
