post:
  summary: Application instance was enabled
  operationId: application-instance-enabled
  x-products:
    - Users
  tags:
    - Application owners
  requestBody:
    $ref: ../components/requestBodies/ApplicationInstanceEnabled.yaml
  responses:
    2xx:
      description: Returns any 2xx status to indicate that the data received.
