# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/paths/authentication-options.yaml:
  no-http-verbs-in-paths:
    - '#/'
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/customers@{id}@lead-source.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/files@{id}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/invoices@{id}@items@{itemId}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/kyc-settings.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/email-delivery-setting-verifications@{token}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/events@{eventType}@rules.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/gateway-accounts@{id}@downtime-schedules@{downtimeId}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/grid-segments@{id}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/profile.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/external-services-settings.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
