# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/openapi.yaml:
  description-capitalization assertion:
    - '#/info/description'
  description-punctuation assertion:
    - '#/info/description'
openapi/paths/authentication-options.yaml:
  no-http-verbs-in-paths:
    - '#/'
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/customers@{id}@lead-source.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/files@{id}.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/invoices@{id}@items@{itemId}.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/kyc-settings.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/email-delivery-setting-verifications@{token}.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/events@{eventType}@rules.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/gateway-accounts@{id}@downtime-schedules@{downtimeId}.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/grid-segments@{id}.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/profile.yaml:
  put-200-and-201 assertion:
    - '#/put/responses'
openapi/paths/credential-hashes@avalara@{hash}.yaml:
  path-segment-plural:
    - '#/'
