apis:
  openapi:
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
  plugins:
    - ./plugins/custom-rules.js
    - ./plugins/products-bundler/bundler.js
  rules:
    assertions:
      - subject: Tag
        property: description
        message: Tag description must be at least 30 characters and end with a full stop.
        severity: error
        defined: true
        minLength: 30
        pattern: /\.$/
      - subject: Operation
        property: description
        message: Operation description must be at least 30 characters and end with a full stop.
        severity: error
        defined: true
        minLength: 30
        pattern: /\.$/
      - subject: Info
        property: description
        message: Info description must be at least 30 characters and end with a full stop.
        severity: error
        defined: true
        minLength: 30
        pattern: /\.$/
      - subject: Operation
        property: summary
        message: Operation summary must be between 20 and 60 characters and not end with a full stop.
        severity: error
        defined: true
        minLength: 20
        maxLength: 60
        pattern: /[^\.]$/
    no-ambiguous-paths: error
    no-unused-components: error
    operation-2xx-response: error
    operation-operationId: error
    operation-singular-tag: error
    operation-4xx-response: off
    tag-description: off
    custom-rules/description-punctuation: error
    custom-rules/has-sdk-operation-name: error
    custom-rules/no-unused-tags: warn
  decorators:
    products-bundler/bundle: error
features.openapi:
  pagination: section
  theme:
    logo:
      gutter: 20px 30px 14px 30px
    colors:
      primary:
        main: '#0044D4'
      text:
        primary: '#0D2B3E'
    typography:
      headings:
        fontFamily: Roboto
      fontFamily: 'Roboto, Verdana, Geneva, sans-serif'
      fontSize: 14px
      code:
        fontFamily: '"Courier New",monospace'
      rightPanelHeading:
        color: white
    rightPanel:
      backgroundColor: '#505A6F'
    codeBlock:
      backgroundColor: '#0D2B3E'
    links:
      color: '#6CC496'
  htmlTemplate: ./web/index.html
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: Node.js
      - lang: C#
      - lang: Python
      - lang: Java
      - lang: Go
      - lang: Ruby
      - lang: PHP
  schemaExpansionLevel: '2'
  maxDisplayedEnumValues: 10
  showConsole: true
  expandResponses: '200,201'
