apiDefinitions:
  core: openapi/core.yaml
  users: openapi/users.yaml
  reports: openapi/reports.yaml
  combined: openapi/combined.yaml
lint:
  rules:
    no-unused-schemas: warning
  transformers: ./transformers/index.js
referenceDocs:
  showConsole: true
  layout:
    scope: section
  theme:
    logo:
      gutter: 20px 30px 14px 30px
    colors:
      text:
        primary: '#333333'
    typography:
      headings:
        fontFamily: Roboto
      fontFamily: 'Roboto, Verdana, Geneva, sans-serif'
      fontSize: 14px
      code:
        fontFamily: '"Courier New",monospace'
        tokens:
          token.property:
            color: '#aofbaa'
          string:
            color: '#aofbaa'
      rightPanelHeading:
        color: white
    rightPanel:
      backgroundColor: '#263238'
    links:
      color: '#6CC496'
  htmlTemplate: ./web/index.html
