# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/paths/authentication-options.yaml:
  no-http-verbs-in-paths:
    - '#/'
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/customers@{id}@lead-source.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/files@{id}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/invoices@{id}@items@{itemId}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/kyc-settings.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/email-delivery-setting-verifications@{token}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/components/schemas/Rules/Actions/create-infusionsoft-order.yaml:
  rule/schema-properties-camelCase:
    - '#/allOf/1/properties/contactBody/properties/email_addresses'
    - '#/allOf/1/properties/contactBody/properties/phone_numbers'
    - '#/allOf/1/properties/orderBody/properties/order_date'
    - '#/allOf/1/properties/orderBody/properties/order_title'
    - '#/allOf/1/properties/orderBody/properties/order_type'
openapi/paths/events@{eventType}@rules.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/gateway-accounts@{id}@downtime-schedules@{downtimeId}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/grid-segments@{id}.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/profile.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
openapi/paths/external-services-settings.yaml:
  rule/put-200-and-201:
    - '#/put/responses'
