# Do not allow installation of dependencies or transitive dependencies that
# are not at least 24 hours old. This is to reduce the risk of installing compromised packages.
minimumReleaseAge: 1440
onlyBuiltDependencies:
  - core-js
  - protobufjs
