get:
  x-products:
    - Storefront
  tags:
    - Products
  summary: Retrieve products
  operationId: StorefrontGetProductCollection
  x-sdk-operation-name: getAll
  description: Retrieve a list of products.
  parameters:
    - $ref: ../../components/parameters/collectionFilter.yaml
    - $ref: ../../components/parameters/collectionSort.yaml
    - $ref: ../../components/parameters/collectionLimit.yaml
    - $ref: ../../components/parameters/collectionOffset.yaml
    - $ref: ../../components/parameters/collectionQuery.yaml
  responses:
    200:
      description: List of products retrieved.
      headers:
        Pagination-Total:
          $ref: ../../components/headers/Pagination-Total.yaml
        Pagination-Limit:
          $ref: ../../components/headers/Pagination-Limit.yaml
        Pagination-Offset:
          $ref: ../../components/headers/Pagination-Offset.yaml
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../../components/schemas/Storefront/StorefrontProduct.yaml
    401:
      $ref: ../../components/responses/Unauthorized.yaml
    403:
      $ref: ../../components/responses/Forbidden.yaml
