parameters:
  - $ref: ../../components/parameters/organizationId.yaml
get:
  tags:
    - Product
  summary: Retrieve a list of products
  operationId: StorefrontGetProductCollection
  description: |
    Retrieve a list of products
  parameters:
    - $ref: ../../components/parameters/collectionLimit.yaml
    - $ref: ../../components/parameters/collectionOffset.yaml
  responses:
    200:
      description: A list of products was retrieved successfully
      headers:
        Pagination-Total:
          $ref: ../../components/headers/Pagination-Total.yaml
        Pagination-Limit:
          $ref: ../../components/headers/Pagination-Limit.yaml
        Pagination-Offset:
          $ref: ../../components/headers/Pagination-Offset.yaml
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../../components/schemas/Common/CommonProduct.yaml
    401:
      $ref: ../../components/responses/Unauthorized.yaml
    403:
      $ref: ../../components/responses/Forbidden.yaml
