parameters:
  - $ref: ../components/parameters/resourceId.yaml
  - $ref: ../components/parameters/organizationId.yaml
get:
  x-products:
    - Users
  tags:
    - Application owners
  summary: Retrieve an application instance
  operationId: GetApplicationInstanceByOrganization
  x-sdk-operation-name: getInstance
  description: >-
    Retrieves an application instance with specified application and
    organization IDs.
  responses:
    '200':
      description: Application instance retrieved.
      headers:
        Pagination-Total:
          $ref: ../components/headers/Pagination-Total.yaml
        Pagination-Limit:
          $ref: ../components/headers/Pagination-Limit.yaml
        Pagination-Offset:
          $ref: ../components/headers/Pagination-Offset.yaml
      content:
        application/json:
          schema:
            $ref: ../components/schemas/OwnerApplicationInstance.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
  x-codeSamples:
    - lang: PHP
      source:
        $ref: >-
          ../code_samples/PHP/applications_{id}_instances_{organizationId}/getundefined
    - lang: JavaScript
      source:
        $ref: >-
          ../code_samples/JavaScript/applications_{id}_instances_{organizationId}/getundefined
