type: object
description: Application instance object.
properties:
  status:
    description: Status of the application instance.
    readOnly: true
    type: string
    enum:
      - enabling
      - enabled
      - disabling
      - disabled
  isConfigured:
    description: |-
      Determines if the configuration of the application instance is complete.
      Configuration is completed using the [Upsert an application instance configuration](https://www.rebilly.com/catalog/all/application-users/putapplicationinstanceconfiguration) operation.
    type: boolean
    readOnly: true
  settings:
    description: Configuration settings that are available during installation.
    type: object
    additionalProperties:
      type: string
      description: Additional properties that the user adds when installing an application.
    example:
      color: red
      limit: '5'
    deprecated: true
    readOnly: true
  createdTime:
    $ref: ./CreatedTime.yaml
  updatedTime:
    $ref: ./UpdatedTime.yaml
  _links:
    $ref: ./SelfLink.yaml
