type: object
description: Settings for KYC score calculation.
properties:
  identityProof:
    $ref: ./KycDocument/Settings/KycSettingsIdentity.yaml
  addressProof:
    $ref: ./KycDocument/Settings/KycSettingsAddress.yaml
