type: object
description: Settings for KYC score calculation.
properties:
  identityProof:
    $ref: ./KycSettingsIdentity.yaml
  addressProof:
    $ref: ./KycSettingsAddress.yaml
  uiVersion:
    description: Version of the KYC document gatherer UI.
    type:
      - 'string'
      - 'null'
    enum:
      - '1'
      - '2'
    default: '1'
    x-enumDescriptions:
      '1': Classic design.
      '2': Modern design, optimized for the best user experience on both mobile and desktop devices.
