type: object
description: The settings for score calculation.
properties:
  identity-proof:
    $ref: ./KycDocument/Settings/KycSettingsIdentity.yaml
  address-proof:
    $ref: ./KycDocument/Settings/KycSettingsAddress.yaml
