type: object
description: The settings for score calculation.
properties:
  identityProof:
    $ref: ./KycDocument/Settings/KycSettingsIdentity.yaml
  addressProof:
    $ref: ./KycDocument/Settings/KycSettingsAddress.yaml
