type: object
description: The settings for organization notifications.
properties:
  notifyOnUserAccessChanges:
    description: Specifies if a notification should be sent when there are changes in user access.
    type: boolean
    default: false
    example: false
  notifyOnApiKeyAccessChanges:
    description: Specifies if a notification should be sent when there are changes in API key access.
    type: boolean
    default: false
    example: false
  emailAddresses:
    description: List of email addresses where notifications are sent.
    type: array
    items:
      type: string
      format: email
