type: object
description: The settings for organization notifications.
properties:
  notifyOnUserAccessChanges:
    description: >-
      Specifies if a notification should be sent when a new or existing user gains access to the organization
      or when the user permissions of an existing user change.
    type: boolean
    default: false
    example: false
  notifyOnApiKeyAccessChanges:
    description: >-
      Specifies if a notification should be sent when a new or existing API key gains access to the organization
      or when an API key is updated.
    type: boolean
    default: false
    example: false
  emailAddresses:
    description: List of email addresses where notifications are sent.
    type: array
    items:
      type: string
      format: email
