allOf:
  - $ref: Common/CommonProduct.yaml
  - properties:
      taxCategoryId:
        description: |-
          Tax category of the product.
          See a complete list of supported tax categories in [TaxJar sales tax API reference](https://developers.taxjar.com/api/reference/#get-list-tax-categories).
          Use the general tax category `00000` if none of the tax categories from the list are applicable for your product.
        type: string
        example: '00000'
      accountingCode:
        description: Accounting code of the product.
        type: string
        example: '4010'
      _links:
        type: array
        description: The links related to resource.
        readOnly: true
        minItems: 1
        items:
          $ref: ./Links/SelfLink.yaml
