allOf:
  - $ref: Common/CommonProduct.yaml
  - properties:
      taxCategoryId:
        description: The product's tax category identifier string.
        type: string
        enum:
          - '00000'
          - '99999'
          - '20010'
          - '40030'
          - '51020'
          - '51010'
          - '31000'
          - '30070'
      accountingCode:
        description: The product accounting code.
        type: string
        example: '4010'
      _links:
        type: array
        description: The links related to resource.
        readOnly: true
        minItems: 1
        items:
          $ref: ./Links/SelfLink.yaml
