allOf:
  - $ref: Common/CommonProduct.yaml
  - properties:
      taxCategoryId:
        description: |-
          Tax category of the product.
          For a complete list of supported tax categories, see [TaxJar sales tax API reference](https://developers.taxjar.com/api/reference/#get-list-tax-categories).
          If none of the tax categories from the list are applicable for your product, use the general tax category `00000`.
        type: string
        example: '00000'
      accountingCode:
        description: Accounting code of the product.
        type: string
        example: '4010'
      _links:
        type: array
        description: Related resource links.
        readOnly: true
        minItems: 1
        items:
          $ref: ./Links/SelfLink.yaml
