allOf:
  - $ref: ../Application.yaml
  - properties:
        _embedded:
          type: array
          description: >-
            Any embedded objects available that are requested by the `expand`
            querystring parameter.
          readOnly: true
          minItems: 1
          items:
            anyOf:
              - $ref: ../../Embeds/ApplicationInstanceEmbed.yaml