summary: Application instance was updated
operationId: application-instance-updated
x-products:
  - Full
  - Users
tags:
  - Application owners
requestBody:
  $ref: ../components/requestBodies/Webhooks/ApplicationInstanceUpdated.yaml
responses:
  '2xx':
    description: Return any 2xx status to indicate that the data was received successfully.
