summary: Coupon application removed
operationId: coupon-application-removed
x-products:
  - Core
tags:
  - Coupons
requestBody:
  $ref: ../components/requestBodies/Webhooks/CouponRedemptionWebhook.yaml
responses:
  '2xx':
    description: Returns any 2xx status to indicate that the data received.
