summary: Product deactivated
operationId: product-deactivated
x-products:
  - Core
tags:
  - Products
requestBody:
  $ref: ../components/requestBodies/Webhooks/ProductWebhook.yaml
responses:
  '2xx':
    description: Returns any 2xx status to indicate that the data is received.
