type: object
description: Confidence settings.
properties:
  noDobExactMatch:
    type: object
    description: An exact match of the customer's name is found, but a date of birth is not.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  noDobInexactMatch:
    type: object
    description: A fuzzy, or inexact match of the customer's name is found, but a date of birth is not.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  noDobWeakMatch:
    type: object
    description: A weak match of the customer's name is found, but a date of birth is not.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  dobExactMatch:
    type: object
    description: An exact match of the customer's date of birth and name is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  dobInexactMatch:
    type: object
    description: An exact match of the customer's date of birth and a fuzzy, or inexact name match is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  yobExactMatch:
    type: object
    description: An exact match of the customer's year of birth and exact name is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  yobInexactMatch:
    type: object
    description: An exact match of the customer's year of birth and an inexact name match is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  inexactYobExactMatch:
    type: object
    description: A fuzzy, or inexact match of the customer's year of birth and an exact name match is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  inexactYobInexactMatch:
    type: object
    description: A fuzzy, or inexact match of the customer's year of birth and a fuzzy, or inexact name match is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml

