type: object
description: Confidence settings.
properties:
  noDobExactMatch:
    type: object
    description: No date of birth with an exact match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  noDobInexactMatch:
    type: object
    description: No date of birth with a fuzzy match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  noDobWeakMatch:
    type: object
    description: No date of birth with a weak fuzzy match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  dobExactMatch:
    type: object
    description: Matching date of birth with an exact match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  dobInexactMatch:
    type: object
    description: Matching date of birth with a fuzzy match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  yobExactMatch:
    type: object
    description: Matching year of birth with an exact match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  yobInexactMatch:
    type: object
    description: Matching year of birth with a fuzzy match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  inexactYobExactMatch:
    type: object
    description: Near matching year of birth with an exact match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  inexactYobInexactMatch:
    type: object
    description: Near matching year of birth with a fuzzy match on the name.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml

