type: object
description: Confidence level settings for AML matches.
properties:
  noDobExactMatch:
    type: object
    description: Exact match of the customer's name is found, but a date of birth is not.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  noDobInexactMatch:
    type: object
    description: Fuzzy, or inexact match of the customer's name is found, but a date of birth is not.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  noDobWeakMatch:
    type: object
    description: Weak match of the customer's name is found, but a date of birth is not.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  dobExactMatch:
    type: object
    description: Exact match of the customer's date of birth and name is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  dobInexactMatch:
    type: object
    description: Exact match of the customer's date of birth and a fuzzy, or inexact name match is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  yobExactMatch:
    type: object
    description: Exact match of the customer's year of birth and exact name is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  yobInexactMatch:
    type: object
    description: Exact match of the customer's year of birth and a fuzzy, or inexact name match is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  inexactYobExactMatch:
    type: object
    description: Near match of the customer's year of birth and an exact name match is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml
  inexactYobInexactMatch:
    type: object
    description: Near match of the customer's year of birth and a fuzzy, or inexact name match is found.
    properties:
      matchingCountry:
        $ref: ./AmlConfidence.yaml
      mismatchingCountry:
        $ref: ./AmlConfidence.yaml
      noCountry:
        $ref: ./AmlConfidence.yaml

