description: >
  Applications in our App Store can create a JSON Web Token (JWT) by [fetching an user's
  instance](https://user-api-docs.rebilly.com/tag/Application-owners#operation/GetApplicationInstanceByOrganization).

  Usage format: `Bearer <JWT>`.
type: http
scheme: bearer
bearerFormat: JWT
