type: object
description: Set of rules for particular event.
properties:
  versionHash:
    type: string
  binds:
    type: array
    readOnly: true
    items:
      $ref: ./Bind.yaml
  rules:
    type: array
    readOnly: true
    items:
      $ref: ./Rule.yaml
  updatedTime:
    $ref: ../ServerTimestamp.yaml
  _links:
    type: array
    description: The links related to resource.
    readOnly: true
    minItems: 1
    items:
      $ref: ../Links/SelfLink.yaml
required:
  - versionHash
