type: object
description: Financial settings.
properties:
  riskReserveSettings:
    description: |-
      Risk reserve settings.
      Use these settings to set up funds reserves before settlement.
    type: array
    items:
      type: object
      required:
        - filter
        - bips
        - period
      properties:
        filter:
          description: Filter that is based on the properties of the transaction and used to determine when to apply the settings.
          minLength: 1
          maxLength: 255
          example: 'paymentInstrument.method:payment-card'
          type: string
        bips:
          $ref: ../Bips.yaml
        period:
          $ref: RiskReservePeriod.yaml
  settlementSettings:
    description: |-
      Settlement settings.
      Use these settings to set up settlement accounts.
    type: object
    required:
      - settlementCurrency
      - settlementPeriod
    properties:
      settlementCurrency:
        description: Default settlement currency for all transactions.
        allOf:
          - $ref: ../CurrencyCode.yaml
      settlementPeriod:
        description: Default settlement period for all transactions.
        allOf:
          - $ref: SettlementPeriod.yaml
      advancedSettings:
        description: |-
          Advanced settlement settings.
          Use these settings to override either default settlement currency,
          period, or both for the transactions matched a filter.
        type: array
        items:
          type: object
          required:
            - filter
          properties:
            filter:
              type: string
              description: Filter that is based on transaction properties and is used to determine when to apply the settings.
              minLength: 1
              maxLength: 255
              example: 'currency:EUR,GBP'
            settlementCurrency:
              $ref: ../CurrencyCode.yaml
            settlementPeriod:
              $ref: SettlementPeriod.yaml
