type: object
required:
  - name
  - description
  - logoId
  - permissions
properties:
  id:
    description: The application identifier string.
    readOnly: true
    allOf:
      - $ref: ../ResourceId.yaml
  name:
    description: The application name.
    type: string
  description:
    description: The application description.
    type: string
  status:
    description: The application status.
    readOnly: true
    type: string
    enum:
      - pending-approval
      - available
      - disabled
  logoId:
    description: The application logo ID.
    allOf:
      - $ref: ../ResourceId.yaml
  permissions:
    description: The list of permissions available to the application.
    type: array
    items:
      type: string
      format: operationId
    example:
      - PostFile
      - StorefrontGetAccount
      - StorefrontGetWebsite
      - StorefrontGetKycDocumentCollection
      - StorefrontGetKycDocument
      - StorefrontPostKycDocument
  properties:
    description: The list of application properties.
    type: array
    items:
      $ref: ./ApplicationProperty.yaml
  createdTime:
    description: Application created time.
    allOf:
      - $ref: ../ServerTimestamp.yaml
  updatedTime:
    description: Application updated time.
    allOf:
      - $ref: ../ServerTimestamp.yaml
  _links:
    type: array
    description: The links related to resource.
    readOnly: true
    minItems: 1
    items:
      anyOf:
        - $ref: ../Links/SelfLink.yaml
        - $ref: ../Links/ApplicationInstanceLink.yaml
  _embedded:
    type: array
    description: >-
      Any embedded objects available that are requested by the `expand`
      querystring parameter.
    readOnly: true
    minItems: 1
    items:
      anyOf:
        - $ref: ../Embeds/ApplicationInstanceEmbed.yaml
