type: object
required:
  - name
  - logoId
  - authorName
  - tagline
  - description
  - permissions
properties:
  id:
    description: The application identifier string.
    readOnly: true
    allOf:
      - $ref: ../ResourceId.yaml
  name:
    description: The application name.
    type: string
  logoId:
    description: The application logo ID.
    allOf:
      - $ref: ../ResourceId.yaml
  authorName:
    description: The author's name.
    type: string
  authorLogoId:
    description: The author's logo ID.
    allOf:
      - $ref: ../ResourceId.yaml
  tagline:
    description: The application's tagline.
    type: string
  description:
    description: The application description.
    type: string
  status:
    description: The application status.
    readOnly: true
    type: string
    enum:
      - pending-approval
      - available
      - disabled
  permissions:
    description: The list of permissions available to the application.
    type: array
    items:
      type: string
      format: operationId
    example:
      - PostFile
      - StorefrontGetAccount
      - StorefrontGetWebsite
      - StorefrontGetKycDocumentCollection
      - StorefrontGetKycDocument
      - StorefrontPostKycDocument
  properties:
    description: >-
      The list of application properties.
      This is a JSON-schema object.
    type: object
    example: 
      type: object
      properties:
        email:
          type: "string"
        max:
          type: "integer"
          minimum: 0
          exclusiveMaximum: 100
      required: ["email"]
  createdTime:
    description: Application created time.
    allOf:
      - $ref: ../ServerTimestamp.yaml
  updatedTime:
    description: Application updated time.
    allOf:
      - $ref: ../ServerTimestamp.yaml
  _links:
    type: array
    description: The links related to resource.
    readOnly: true
    minItems: 1
    items:
      anyOf:
        - $ref: ../Links/SelfLink.yaml
        - $ref: ../Links/ApplicationInstanceLink.yaml
        - $ref: ../Links/LogoUrlLink.yaml
        - $ref: ../Links/AuthorLogoUrlLink.yaml
