allOf:
  - $ref: ../ApplicationInstance.yaml
  - properties:
      organizationId:
        description: The merchant identifier string.
        allOf:
          - $ref: ../../ResourceId.yaml
        readOnly: true
      token:
        description: The session's token used to authenticate as the merchant.
        type: string
        readOnly: true
