allOf:
  - properties:
      organizationId:
        description: The user's ID.
        allOf:
          - $ref: ../../ResourceId.yaml
        readOnly: true
      token:
        description: The session's token used to authenticate as the merchant.
        type: string
        readOnly: true
  - $ref: ../ApplicationInstance.yaml
