type: object
required:
  - name
description: |
  Products include digital goods, services, and physical goods.
  Products appear on invoice line items. If you set a tax category identifier,
  taxes will be calculated upon invoice generation. If it is shippable,
  shipping will be calculated upon invoice generation. Pricing and
  variations are set within Plans.
properties:
  id:
    description: The product ID
    readOnly: true
    allOf:
      - $ref: ../ResourceId.yaml
    example: membership
  name:
    description: The product name
    type: string
    maxLength: 255
    example: Premium membership
  unitLabel:
    description: The unit label, such as per `seat` or per `unit`.
    type: string
    maxLength: 50
    example: seat
    default: unit
  description:
    description: The product description
    type: string
    maxLength: 512
  requiresShipping:
    description: If the product requires shipping, shipping calculations will be applied.
    type: boolean
    example: false
  options:
    description: |
      The product options such as color, size, etc. The product options definition does
      not include option values. Those are defined within the plans.
    type: array
    items:
      type: string
  customFields:
    $ref: ../ResourceCustomFields.yaml
  createdTime:
    description: The product created time
    allOf:
      - $ref: ../ServerTimestamp.yaml
  updatedTime:
    description: The product updated time
    allOf:
      - $ref: ../ServerTimestamp.yaml
